const translations = {
    vi: {
        title: "Made For Aisyah 🎁",
        description: "Một món quà đầy yêu thương đang chờ bạn khám phá! Nhấn để xem lời chúc đặc biệt!",
        login: "Đăng nhập bằng Google",
        logout: "Đăng xuất",
        settings: "Cài Đặt Trang Web",
        music: "Cài Đặt Âm Thanh",
        backgroundMusic: "Nhạc Nền:",
        countdown: "Cài Đặt Thời Gian",
        countdownTime: "Thời Gian Đếm Ngược:",
        matrix: "Cài Đặt Hiệu Ứng Mưa Chữ",
        matrixText: "chữ chính mưa chữ:",
        matrixColor1: "Màu mưa chữ 1:",
        matrixColor2: "Màu mưa chữ 2:",
        sequence: "Cài Đặt chữ chính",
        sequenceText: "Nội Dung chữ chính:",
        sequenceColor: "Màu chữ chính:",
        gift: "Cài Đặt Hình Động",
        giftImage: "Hình Động (tùy chọn):",
        enableBook: "Hiển thị sách:",
        book: "Cài Đặt Trang Sách",
        enableHeart: "Hiển thị hiệu ứng trái tim:",
        note: "⏳ Lưu ý: Hạn sử dụng chỉ có 7 ngày, vậy nên đừng tạo trước quá sớm nhé!",
        follow: "🥰 Hãy follow mình để cập nhật những website mới nhất, nhanh nhất nhé!",
        apply: "Áp Dụng Cài Đặt",
        copyright: 'Website được tạo bởi tiktoker: <a href="https://www.tiktok.com/@iamtritoan?is_from_webapp=1&sender_device=pc" target="_blank"> @iamtritoan</a>',
        fullscreen: "Toàn màn hình",
        // ...thêm các key khác nếu cần...
        pricingTitle: "Bảng Giá Dịch Vụ",
        voucher: "Voucher giảm giá:",
        tip: "💸 Tip cho tác giả:",
        total: "Tổng cộng:",
        createWebsite: "🎉 Tạo Website",
        payAndCreate: "💳 Thanh toán & Tạo Website",
        defaultConfig: "🎉 Sử dụng cấu hình mặc định - MIỄN PHÍ!",
        customMusic: "Nhạc nền tùy chỉnh",
        book: "Sách kỷ niệm",
        extraPage: "Trang thêm",
        heartEffect: "Hiệu ứng trái tim (trong sách)",
        tipAuthor: "Tip cho tác giả",
        voucherApplied: "✅ Đã áp dụng voucher: {code} (-{discount}%)",
        loadingVoucher: "Đang tải voucher...",
        noVoucher: "Bạn không có voucher nào cả!",
        needLoginVoucher: "Bạn cần đăng nhập để xem voucher!",
        cannotLoadVoucher: "Không thể tải voucher!",
        copyLink: "📋 Copy Link",
        viewWebsite: "🔗 Xem Website",
        close: "✖ Đóng",
        createSuccess: "🎉 Tạo website thành công!",
        price: "Giá:",
        shareLink: "Link chia sẻ:",
        copySuccess: "Đã copy link sản phẩm!",
        needLogin: "❌ Bạn cần đăng nhập để tạo website! Nút đăng nhập trên góc trái nhé",
        minPay: "❌ Số tiền thanh toán tối thiểu là 10.000 VNĐ!",
        error: "❌ Có lỗi xảy ra!",
        invalidPage: "❌ Cấu trúc trang không hợp lệ! Hiện tại có {pages} trang. Vui lòng thêm hoặc xóa 1 trang để tạo cấu trúc hợp lệ.",
        uploading: "📤 Đang upload ảnh trang sách...",
        creating: "🌐 Đang tạo website...",
        creatingProduct: "📦 Đang tạo sản phẩm...",
        applyingVoucher: "🎫 Đang áp dụng voucher...",
        applyVoucherSuccess: "✅ Áp dụng voucher thành công!",
        applyVoucherFail: "⚠️ Lỗi áp dụng voucher, tiếp tục thanh toán với giá gốc",
        cannotCreate: "Không thể tạo website",
        cannotCreateProduct: "Lỗi khi tạo sản phẩm",
        cannotApplyVoucher: "Áp dụng voucher thất bại!",
        cannotPay: "Lỗi xử lý thanh toán: ",
        paymentRedirect: "🔄 Đang chuyển đến trang thanh toán...",
        free: "MIỄN PHÍ",
        thanks: "Cảm ơn bạn rất nhiều! Nếu thích sản phẩm này, hãy follow kênh TikTok <b>tớ là Toán</b> để mình có động lực ra nhiều sản phẩm hơn nhé!",
        tiktokBtn: "🥰 xem kênh TikTok",
        heartQr: "❤️ Tạo QR trái tim",
        heartQrCopy: "✅ Đã copy link QR trái tim!",
        copyShare: "📋 Sao chép link",
        copied: "✅ Đã sao chép!",
        copyToClipboard: "📋 Đã sao chép link vào clipboard!",
        copyFail: "❌ Không thể sao chép link!",

        //
        validCoverOnly: "✅ Hợp lệ (chỉ có bìa)",
        validCoverAndPairs: "✅ Hợp lệ (bìa + các cặp trang)",
        invalidMissingPage: "❌ Không hợp lệ (thiếu 1 trang để tạo cặp)",
        bookPageInfo: "Thông tin trang sách:",
        totalPages: "Tổng số trang",
        status: "Trạng thái",
        structure: "Cấu trúc",
        coverOnly: "Chỉ có bìa",
        coverAndPairs: "Bìa (1) + {pairs} cặp trang{extra}",
        plusOneExtra: " + 1 trang lẻ",
        pageTitleCover: "Trang {num} (Bìa)",
        pageTitle: "Trang {num}",
        imageLabel: "Hình ảnh:",
        coverPlaceholder: "Bìa Sách",
        pagePlaceholder: "Trang {num}",
        noImageAlt: "Chưa có ảnh - {placeholder}",
        contentLabel: "Nội dung:",
        contentPlaceholder: "Nhập nội dung cho trang {num}",
        addNewPage: "➕ Thêm Trang Mới",
        emptyPage: "Trang trống",
        endOfBook: "Hết sách",
        loading: "Preparing something special...",
        waitingIsHappiness: "Good things take time.",
        invalidPageStructure: "Cấu trúc trang không hợp lệ!",
        currentPages: "Hiện tại có {total} trang.",
        bookStructureGuide: "Cấu trúc sách cần:\n- Trang 1: Bìa\n- Từ trang 2 trở đi: Các cặp trang (2-3, 4-5, 6-7...)",
        pleaseAddOrRemovePage: "Vui lòng thêm thêm 1 trang hoặc xóa bớt 1 trang để tạo cấu trúc hợp lệ.",
        fullscreenNotSupported: "Trình duyệt của bạn không hỗ trợ chế độ toàn màn hình!",
        noteSequence: "lưu ý: hãy ngăn cách bằng dấu | để tách từ, không nên để một dòng quá dài",
        noteExpire: "⏳ <b>Lưu ý:</b> Hạn sử dụng chỉ có <b>30 ngày</b>, vậy nên đừng tạo trước quá sớm nhé!",
        followNote: "🥰 Hãy <a href=\"https://www.tiktok.com/@iamtritoan?is_from_webapp=1&sender_device=pc\" target=\"_blank\" style=\"color:#ff0050;font-weight:bold;text-decoration:underline;\">follow mình</a> để cập nhật những website mới nhất, nhanh nhất nhé!",
        on: "Bật",
        off: "Tắt",
        sec3: "3 giây",
        sec5: "5 giây",
        sec10: "10 giây",
        noGif: "Không có",
        notVietnamWarning: 'Nếu gặp vấn đề hãy nhắn tin qua TikTok<a href="https://www.tiktok.com/@iamtritoan?is_from_webapp=1&sender_device=pc" target="_blank" style="color:#ff0050;font-weight:bold;text-decoration:underline;"> @iamtritoan</a> để được hỗ trợ.',
        isSave: "Lưu QR vĩnh viễn:",
        saveForever: "vĩnh viễn",
        saveForeverPrice: "(Thêm 20.000đ)",
        thirtyDays: "30 ngày",
        expireText: "Hạn sử dụng là",
        colorTheme: "Chọn màu:",
        settingsHint: "ấn vào đây để setting theo ý muốn",
        pinkTheme: "Hồng ngọt ngào",
        blueTheme: "Xanh dương mát mẻ",
        purpleTheme: "Tím mộng mơ",
        customTheme: "Tùy chỉnh màu",
        paymentMethod: "Phương thức thanh toán",
        bankPayment: "Ngân hàng",
        bankPaymentDesc: "Chỉ dành cho người dùng Việt Nam",
        paypalPayment: "Ví PayPal",
        paypalPaymentDesc: "Dành cho người dùng quốc tế",
    },
    en: {
        title: "Special Gift for You 🎁",
        description: "A special gift is waiting for you to discover! Press to see the special message!",
        login: "Sign in with Google",
        logout: "Logout",
        settings: "Website Settings",
        music: "Music Settings",
        backgroundMusic: "Background Music:",
        countdown: "Countdown Settings",
        countdownTime: "Countdown Time:",
        matrix: "Matrix Rain Effect Settings",
        matrixText: "Matrix main text:",
        matrixColor1: "Matrix color 1:",
        matrixColor2: "Matrix color 2:",
        sequence: "Main Text Settings",
        sequenceText: "Main text content:",
        sequenceColor: "Main text color:",
        gift: "Animated Image Settings",
        giftImage: "Animated Image (optional):",
        enableBook: "Show book:",
        book: "Book Page Settings",
        enableHeart: "Show heart effect:",
        note: "⏳ Note: The website is valid for only 7 days, so don't create it too early!",
        follow: "🥰 Please follow me to get the latest websites as soon as possible!",
        apply: "Apply Settings",
        copyright: 'Website created by tiktoker:<a href="https://www.tiktok.com/@iamtritoan?is_from_webapp=1&sender_device=pc" target="_blank"> @iamtritoan</a>',
        fullscreen: "Fullscreen",
        // ...add more keys as needed...

        pricingTitle: "Service Pricing",
        voucher: "Discount voucher:",
        tip: "💸 Tip for author:",
        total: "Total:",
        createWebsite: "🎉 Create Website",
        payAndCreate: "💳 Pay & Create Website",
        defaultConfig: "🎉 Using default configuration - FREE!",
        customMusic: "Custom background music",
        book: "Memory book",
        extraPage: "Extra page",
        heartEffect: "Heart effect (in book)",
        tipAuthor: "Tip for author",
        voucherApplied: "✅ Voucher applied: {code} (-{discount}%)",
        loadingVoucher: "Loading vouchers...",
        noVoucher: "You have no vouchers!",
        needLoginVoucher: "You need to login to see vouchers!",
        cannotLoadVoucher: "Cannot load vouchers!",
        copyLink: "📋 Copy Link",
        viewWebsite: "🔗 View Website",
        close: "✖ Close",
        createSuccess: "🎉 Website created successfully!",
        price: "Price:",
        shareLink: "Share link:",
        copySuccess: "Link copied!",
        needLogin: "❌ Please login to create website!",
        minPay: "❌ Minimum payment is 10,000 VND!",
        error: "❌ An error occurred!",
        invalidPage: "❌ Invalid page structure! Currently {pages} pages. Please add or remove 1 page for valid structure.",
        uploading: "📤 Uploading book images...",
        creating: "🌐 Creating website...",
        creatingProduct: "📦 Creating product...",
        applyingVoucher: "🎫 Applying voucher...",
        applyVoucherSuccess: "✅ Voucher applied successfully!",
        applyVoucherFail: "⚠️ Voucher error, continue with original price",
        cannotCreate: "Cannot create website",
        cannotCreateProduct: "Error creating product",
        cannotApplyVoucher: "Voucher apply failed!",
        cannotPay: "Payment error: ",
        paymentRedirect: "🔄 Redirecting to payment page...",
        free: "FREE",
        thanks: "Thank you so much! If you like this product, please follow my TikTok channel <b>tớ là Toán</b> to motivate me to make more!",
        tiktokBtn: "🥰 View TikTok channel",
        heartQr: "❤️ Create heart QR",
        heartQrCopy: "✅ Heart QR link copied!",
        copyShare: "📋 Copy link",
        copied: "✅ Copied!",
        copyToClipboard: "📋 Link copied to clipboard!",
        copyFail: "❌ Cannot copy link!",

        //
        validCoverOnly: "✅ Valid (cover only)",
        validCoverAndPairs: "✅ Valid (cover + page pairs)",
        invalidMissingPage: "❌ Invalid (missing 1 page to form a pair)",
        bookPageInfo: "Book page info:",
        totalPages: "Total pages",
        status: "Status",
        structure: "Structure",
        coverOnly: "Cover only",
        coverAndPairs: "Cover (1) + {pairs} page pairs{extra}",
        plusOneExtra: " + 1 extra page",
        pageTitleCover: "Page {num} (Cover)",
        pageTitle: "Page {num}",
        imageLabel: "Image:",
        coverPlaceholder: "Book Cover",
        pagePlaceholder: "Page {num}",
        noImageAlt: "No image yet - {placeholder}",
        contentLabel: "Content:",
        contentPlaceholder: "Enter content for page {num}",
        addNewPage: "➕ Add New Page",
        emptyPage: "Empty page",
        endOfBook: "End of book",
        loading: "Loading...",
        waitingIsHappiness: "Waiting is happiness!",
        invalidPageStructure: "Invalid page structure!",
        currentPages: "Currently {total} pages.",
        bookStructureGuide: "Book structure required:\n- Page 1: Cover\n- From page 2: Page pairs (2-3, 4-5, 6-7...)",
        pleaseAddOrRemovePage: "Please add or remove 1 page to create a valid structure.",
        fullscreenNotSupported: "Your browser does not support fullscreen mode!",
        // Thêm vào cả vi và en:
        noteSequence: "Note: Please separate words with | and don't make a line too long",
        noteExpire: "⏳ <b>Note:</b> The website is only valid for <b>30 days</b>, so don't create it too early!",
        followNote: "🥰 Please <a href=\"https://www.tiktok.com/@iamtritoan?is_from_webapp=1&sender_device=pc\" target=\"_blank\" style=\"color:#ff0050;font-weight:bold;text-decoration:underline;\">follow me</a> to get the latest websites as soon as possible!",
        on: "On",
        off: "Off",
        sec3: "3 seconds",
        sec5: "5 seconds",
        sec10: "10 seconds",
        noGif: "None",
        notVietnamWarning: 'If you encounter any issues, please message me on TikTok<a href="https://www.tiktok.com/@iamtritoan?is_from_webapp=1&sender_device=pc" target="_blank" style="color:#ff0050;font-weight:bold;text-decoration:underline;"> @iamtritoan</a> for support.',
        isSave: "Save QR forever:",
        saveForever: "forever",
        saveForeverPrice: "(Add 20,000 VND)",
        thirtyDays: "30 days",
        expireText: "Expiration is",
        colorTheme: "Choose color:",
        settingsHint: "click here to customize settings",
        pinkTheme: "Sweet Pink",
        blueTheme: "Cool Blue",
        purpleTheme: "Dreamy Purple",
        customTheme: "Custom Color",

        paymentMethod: "Payment Method",
        bankPayment: "Bank Transfer",
        bankPaymentDesc: "For Vietnam users only",
        paypalPayment: "PayPal Wallet",
        paypalPaymentDesc: "For international users",
    },
    id: {
        title: "Hadiah Spesial untuk Aisyah 🎁",
        description: "Hadiah penuh cinta sedang menunggu Anda untuk ditemukan! Tekan untuk melihat pesan spesial!",
        login: "Masuk dengan Google",
        logout: "Keluar",
        settings: "Pengaturan Website",
        music: "Pengaturan Musik",
        backgroundMusic: "Musik Latar:",
        countdown: "Pengaturan Hitung Mundur",
        countdownTime: "Waktu Hitung Mundur:",
        matrix: "Pengaturan Efek Hujan Matrix",
        matrixText: "Teks utama matrix:",
        matrixColor1: "Warna matrix 1:",
        matrixColor2: "Warna matrix 2:",
        sequence: "Pengaturan Teks Utama",
        sequenceText: "Konten teks utama:",
        sequenceColor: "Warna teks utama:",
        gift: "Pengaturan Gambar Animasi",
        giftImage: "Gambar Animasi (opsional):",
        enableBook: "Tampilkan buku:",
        book: "Pengaturan Halaman Buku",
        enableHeart: "Tampilkan efek hati:",
        note: "⏳ Catatan: Website hanya berlaku selama 7 hari, jadi jangan buat terlalu awal!",
        follow: "🥰 Silakan follow saya untuk mendapatkan website terbaru secepat mungkin!",
        apply: "Terapkan Pengaturan",
        copyright: 'Website dibuat oleh tiktoker:<a href="https://www.tiktok.com/@iamtritoan?is_from_webapp=1&sender_device=pc" target="_blank"> @iamtritoan</a>',
        fullscreen: "Layar Penuh",

        pricingTitle: "Harga Layanan",
        voucher: "Voucher diskon:",
        tip: "💸 Tip untuk penulis:",
        total: "Total:",
        createWebsite: "🎉 Buat Website",
        payAndCreate: "💳 Bayar & Buat Website",
        defaultConfig: "🎉 Menggunakan konfigurasi default - GRATIS!",
        customMusic: "Musik latar kustom",
        book: "Buku kenangan",
        extraPage: "Halaman tambahan",
        heartEffect: "Efek hati (dalam buku)",
        tipAuthor: "Tip untuk penulis",
        voucherApplied: "✅ Voucher diterapkan: {code} (-{discount}%)",
        loadingVoucher: "Memuat voucher...",
        noVoucher: "Anda tidak memiliki voucher!",
        needLoginVoucher: "Anda perlu login untuk melihat voucher!",
        cannotLoadVoucher: "Tidak dapat memuat voucher!",
        copyLink: "📋 Salin Link",
        viewWebsite: "🔗 Lihat Website",
        close: "✖ Tutup",
        createSuccess: "🎉 Website berhasil dibuat!",
        price: "Harga:",
        shareLink: "Link berbagi:",
        copySuccess: "Link berhasil disalin!",
        needLogin: "❌ Silakan login untuk membuat website!",
        minPay: "❌ Pembayaran minimum adalah 10.000 VND!",
        error: "❌ Terjadi kesalahan!",
        invalidPage: "❌ Struktur halaman tidak valid! Saat ini {pages} halaman. Silakan tambah atau hapus 1 halaman untuk struktur yang valid.",
        uploading: "📤 Mengupload gambar buku...",
        creating: "🌐 Membuat website...",
        creatingProduct: "📦 Membuat produk...",
        applyingVoucher: "🎫 Menerapkan voucher...",
        applyVoucherSuccess: "✅ Voucher berhasil diterapkan!",
        applyVoucherFail: "⚠️ Kesalahan voucher, lanjutkan dengan harga asli",
        cannotCreate: "Tidak dapat membuat website",
        cannotCreateProduct: "Kesalahan membuat produk",
        cannotApplyVoucher: "Penerapan voucher gagal!",
        cannotPay: "Kesalahan pembayaran: ",
        paymentRedirect: "🔄 Mengalihkan ke halaman pembayaran...",
        free: "GRATIS",
        thanks: "Terima kasih banyak! Jika Anda suka produk ini, silakan follow channel TikTok saya <b>tớ là Toán</b> untuk memotivasi saya membuat lebih banyak produk!",
        tiktokBtn: "🥰 Lihat channel TikTok",
        heartQr: "❤️ Buat QR hati",
        heartQrCopy: "✅ Link QR hati berhasil disalin!",
        copyShare: "📋 Salin link",
        copied: "✅ Disalin!",
        copyToClipboard: "📋 Link berhasil disalin ke clipboard!",
        copyFail: "❌ Tidak dapat menyalin link!",

        validCoverOnly: "✅ Valid (hanya sampul)",
        validCoverAndPairs: "✅ Valid (sampul + pasangan halaman)",
        invalidMissingPage: "❌ Tidak valid (kurang 1 halaman untuk membentuk pasangan)",
        bookPageInfo: "Info halaman buku:",
        totalPages: "Total halaman",
        status: "Status",
        structure: "Struktur",
        coverOnly: "Hanya sampul",
        coverAndPairs: "Sampul (1) + {pairs} pasangan halaman{extra}",
        plusOneExtra: " + 1 halaman tambahan",
        pageTitleCover: "Halaman {num} (Sampul)",
        pageTitle: "Halaman {num}",
        imageLabel: "Gambar:",
        coverPlaceholder: "Sampul Buku",
        pagePlaceholder: "Halaman {num}",
        noImageAlt: "Belum ada gambar - {placeholder}",
        contentLabel: "Konten:",
        contentPlaceholder: "Masukkan konten untuk halaman {num}",
        addNewPage: "➕ Tambah Halaman Baru",
        emptyPage: "Halaman kosong",
        endOfBook: "Akhir buku",
        loading: "Memuat...",
        waitingIsHappiness: "Menunggu adalah kebahagiaan!",
        invalidPageStructure: "Struktur halaman tidak valid!",
        currentPages: "Saat ini {total} halaman.",
        bookStructureGuide: "Struktur buku yang diperlukan:\n- Halaman 1: Sampul\n- Dari halaman 2: Pasangan halaman (2-3, 4-5, 6-7...)",
        pleaseAddOrRemovePage: "Silakan tambah atau hapus 1 halaman untuk membuat struktur yang valid.",
        fullscreenNotSupported: "Browser Anda tidak mendukung mode layar penuh!",
        noteSequence: "Catatan: Silakan pisahkan kata dengan | dan jangan buat baris terlalu panjang",
        noteExpire: "⏳ <b>Catatan:</b> Website hanya berlaku selama <b>30 hari</b>, jadi jangan buat terlalu awal!",
        followNote: "🥰 Silakan <a href=\"https://www.tiktok.com/@iamtritoan?is_from_webapp=1&sender_device=pc\" target=\"_blank\" style=\"color:#ff0050;font-weight:bold;text-decoration:underline;\">follow saya</a> untuk mendapatkan website terbaru secepat mungkin!",
        on: "Nyala",
        off: "Mati",
        sec3: "3 detik",
        sec5: "5 detik",
        sec10: "10 detik",
        noGif: "Tidak ada",
        notVietnamWarning: 'Jika Anda mengalami masalah, silakan pesan saya di TikTok<a href="https://www.tiktok.com/@iamtritoan?is_from_webapp=1&sender_device=pc" target="_blank" style="color:#ff0050;font-weight:bold;text-decoration:underline;"> @iamtritoan</a> untuk dukungan.',
        isSave: "Simpan QR selamanya:",
        saveForever: "selamanya",
        saveForeverPrice: "(Tambah 20.000 VND)",
        thirtyDays: "30 hari",
        expireText: "Kedaluwarsa adalah",
        colorTheme: "Pilih warna:",
        settingsHint: "klik di sini untuk mengkustom pengaturan",
        pinkTheme: "Pink Manis",
        blueTheme: "Biru Sejuk",
        purpleTheme: "Ungu Impian",
        customTheme: "Warna Kustom",

        paymentMethod: "Metode Pembayaran",
        bankPayment: "Transfer Bank",
        bankPaymentDesc: "Hanya untuk pengguna Vietnam",
        paypalPayment: "Dompet PayPal",
        paypalPaymentDesc: "Untuk pengguna internasional",
    }
};

function setLanguage(lang) {
    document.documentElement.lang = lang;
    // Đổi title và meta
    document.title = translations[lang].title;
    document.querySelector('meta[name="description"]').setAttribute('content', translations[lang].description);

    // Đổi các phần tử có data-i18n
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[lang][key]) {
            if (
                translations[lang][key].includes('<b>') ||
                translations[lang][key].includes('<a')
            ) {
                el.innerHTML = translations[lang][key];
            } else {
                el.innerText = translations[lang][key];
            }
        }
    });

    // Đổi các placeholder
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
        const key = el.getAttribute('data-i18n-placeholder');
        if (translations[lang][key]) {
            el.setAttribute('placeholder', translations[lang][key]);
        }
    });

    // Đổi các label, option, v.v. nếu cần
    // ...bổ sung nếu cần...
}

// Lưu ngôn ngữ vào localStorage
function switchLanguage() {
    const current = localStorage.getItem('lang') || 'vi';
    let next;
    if (current === 'vi') {
        next = 'en';
    } else if (current === 'en') {
        next = 'id';
    } else {
        next = 'vi';
    }
    localStorage.setItem('lang', next);
    setLanguage(next);
    // Cập nhật lại UI động (nếu có)
    if (window.pricingCalculator) {
        window.pricingCalculator.updatePricing();
    }
    // Cập nhật hiển thị hạn sử dụng khi đổi ngôn ngữ
    if (typeof updateExpireDateDisplay === 'function') {
        updateExpireDateDisplay();
    }
}

// Khởi tạo ngôn ngữ khi load trang
document.addEventListener('DOMContentLoaded', () => {
    const lang = localStorage.getItem('lang') || 'vi';
    setLanguage(lang);
    // Gắn sự kiện cho nút chuyển ngôn ngữ
    document.getElementById('langSwitchBtn').onclick = switchLanguage;
});

function t(key, vars = {}) {
    const lang = localStorage.getItem('lang') || 'vi';
    let str = (translations[lang] && translations[lang][key]) || key;
    Object.keys(vars).forEach(k => {
        str = str.replace(`{${k}}`, vars[k]);
    });
    return str;
}

